#!/bin/bash

#echo "Install git vim, and ssh? [Y/n]"
#read GIT
#if ["$GIT" == 'n' ]; then
 # echo "bypassing installation"
#else
#  sudo apt-get install -y git vim openssh-server
#fi

echo "Install Environment? [Y/n]"
read ENVIRONMENT
if [ "$ENVIRONMENT" == 'n' ]; then
  cd ./environment/color_functions
  bash copy_color_functions
  cd ../..
else
  cd ./environment
  bash install_environment
  cd ..
fi

echo_yellow "Install ROS Melodic? [Y/n]"
read ROS
if [ "$ROS" == 'n' ]; then
  echo_red "bypassing ROS Melodic installation"
else
  ./development/install_kinetic
fi

echo_yellow "Install additional ROS Packages? [Y/n]"
read PACKAGES
if [ "$PACKAGES" == 'n' ]; then
  echo_red "bypassing additional ROS Package installation"
else
  ./development/ros_packages
fi

echo_yellow "Install the ROSflight toolchain? [Y/n]"
read ROSFLIGHT
if [ "$ROSFLIGHT" == 'n' ]; then
  echo_red "bypassing ROSflight toolchain installation"
else
  ./development/ROSflight_toolchain
fi

echo_yellow "Install pixhawk toolchain? [Y/n]"
read PIXHAWK
if [ "$PIXHAWK" == 'n' ]; then
  echo_red "bypassing PixHawk toolchain installaion"
else
  ./development/pixhawk_toolchain
fi

echo_yellow "Install Google Chrome? [Y/n]"
read CHROME
if [ "$CHROME" == 'n' ]; then
  echo_red "bypassing Chrome installation"
else
  ./programs/install_google_chrome
fi

echo_yellow "Install Sublime? [Y/n]"
read SUBLIME
if [ "$SUBLIME" == 'n' ]; then
  echo_red "bypassing Sublime Installation"
else
  programs/install_sublime
fi

echo_yellow "Install Atom? [Y/n]"
read ATOM
if [ "$ATOM" == 'n' ]; then
  echo_red "bypassing atom installation"
else
  programs/install_atom
fi

echo_yellow "Install QtCreator? [Y/n]"
read QT
if [ "$QT" == 'n' ]; then
  echo_red "bypassing QtCreator installation"
else
  ./programs/install_qtcreator
fi

echo_yellow "Install Spotify? [Y/n]"
read SPOTIFY
if [ "$SPOTIFY" == 'n' ]; then
  echo_red "bypassing Spotify installation"
else
  programs/install_spotify
fi

echo_yellow "Install Custom Theme? [Y/n]"
read THEME
if [ "$THEME" == 'n' ]; then
  echo_red "bypassing Theme installation"
else
  ./themes/install_themes
fi
