#!/bin/bash

sudo add-apt-repository -y ppa:gnome-terminator/ppa
sudo apt-get update
sudo apt-get install terminator

mkdir -p ~/.config/terminator
echo  "
[global_config]
  always_on_top = True
  enabled_plugins = CustomCommandsMenu, InactivityWatch, ActivityWatch, TerminalShot, LaunchpadCodeURLHandler, APTURLHandler, Logger, MavenPluginURLHandler, LaunchpadBugURLHandler
  hide_from_taskbar = True
  sticky = True
  title_hide_sizetext = True
  window_state = fullscreen
[keybindings]
  close_term = <Primary>d
  cycle_next = <Shift>Page_Down
  cycle_prev = <Primary><Shift>Page_Up
  go_down = <Primary><Shift>Down
  go_left = <Primary><Shift>Left
  go_next = <Primary><Shift>Right
  go_right = <Primary><Shift>Right
  go_up = <Primary><Shift>Up
  help = F12
  hide_window = F1
  next_tab = <Primary>Page_Down
  prev_tab = <Primary>Page_Up
  zoom_in = <Primary>equal
[layouts]
  [[default]]
    [[[child0]]]
      order = 0
      parent = \"\"
      position = 0:24
      size = 1679, 298
      type = Window
    [[[child1]]]
      order = 0
      parent = child0
      position = 839
      type = HPaned
    [[[terminal2]]]
      order = 0
      parent = child1
      profile = default
      type = Terminal
    [[[terminal3]]]
      order = 1
      parent = child1
      profile = default
      type = Terminal
  [[original]]
    [[[child1]]]
      parent = window0
      profile = default
      type = Terminal
    [[[window0]]]
      order = 0
      parent = \"\"
      type = Window
[plugins]
[profiles]
  [[default]]
    background_darkness = 0.9
    background_image = None
    background_type = transparent
    foreground_color = \"#ffffff\"
" > ~/.config/terminator/confgi
