#!/bin/bash

COFF="\033[0m"
function color_echo    { echo -en "\033[1;33m$@ ${COFF}"; }

if [ "$1" == 'local' ]; then
    export ROS_MASTER_URI=http://localhost:11311
    export ROS_HOSTNAME=localhost
    unset ROS_IP

    color_echo "ROS_MASTER_URI"
    echo = $ROS_MASTER_URI
    color_echo "ROS_HOSTNAME"
    echo = $ROS_HOSTNAME
else
    export ROS_IP=$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/')
    export ROS_MASTER_URI=http://$1:11311
    unset ROS_HOSTNAME

    color_echo "ROS_MASTER_URI"
    echo = $ROS_MASTER_URI
    color_echo "ROS_IP"
    echo = $ROS_IP

fi
