"Convenient tab settings
set tabstop=4
set shiftwidth=2
set softtabstop=2
set expandtab

"Sets xml syntax highlighting for .launch files
au BufRead,BufNewFile *.launch set filetype=xml
au BufRead,BufNewFile *.rosrc set filetype=sh
