#!/bin/bash

sudo add-apt-repository -y ppa:nilarimogard/webupd8
sudo apt-get update
sudo apt-get -y install albert

mkdir -p ~/.config/autostart

echo "
[Desktop Entry]
Name=albert
Exec=albert
Type=Application" > ~/.config/autostart/albert.desktop

