#!/bin/bash

COFF="\033[0m"
function color_echo    { echo -en "\033[1;33m$@ ${COFF}"; }

unset ROS_MASTER_URI
unset ROS_HOSTNAME

if [ "$1" == 'local' ]; then
	export ROS_MASTER_URI=http://localhost:11311
	export ROS_HOSTNAME=localhost

else
	export ROS_MASTER_URI=http://$1:11311
    if [ -z "$2" ]; then
      export ROS_IP=$(hostname -I | awk '{print $NF}')
    else
      export ROS_IP=$(hostname -I | awk -v N=$2 '{print $N}')
    fi
fi

color_echo ROS_MASTER_URI
echo = $ROS_MASTER_URI
if [ -z "$ROS_HOSTNAME" ]; then
  color_echo "ROS_IP"
  echo = $ROS_IP
else
  color_echo "ROS_HOSTNAME"
  echo = $ROS_HOSTNAME
fi
