#!/bin/bash

COFF="\033[0m"
function color_echo    { echo -en "\033[1;33m$@ ${COFF}"; }

LAST4=${1:(-4)}
VPN_FLAG=0
if [ "$LAST4" == '_vpn' ]; then
	VPN_FLAG=1
fi

if [ "$1" == 'local' ]; then
	export ROS_MASTER_URI=http://localhost:11311
	export ROS_HOSTNAME=localhost

else
	export ROS_MASTER_URI=http://$1:11311
	if [ $VPN_FLAG -eq 1 ]; then
		export ROS_HOSTNAME=$USER$LAST4
	else
		export ROS_HOSTNAME=$USER
	fi
fi

color_echo ROS_MASTER_URI
echo = $ROS_MASTER_URI
color_echo "ROS_HOSTNAME"
echo = $ROS_HOSTNAME
