#!/bin/bash

echo_green "********************** Installing Sublime Text 3 ********************"
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt-get update
sudo apt-get install sublime-text


echo_blue "Setting Up Sublime Packages"
wget https://sublime.wbond.net/Package%20Control.sublime-package --no-check-certificate
mkdir -p ~/.config/sublime-text-3/Installed\ Packages
mv Package\ Control.sublime-package ~/.config/sublime-text-3/Installed\ Packages/

mkdir -p  ~/.config/sublime-text-3/Packages/User/Package\ Control
mkdir -p  ~/.config/sublime-text-3/Packages/User

echo_blue "installing Latex"
sudo apt-get install -y texlive latexmk

echo_blue "copying sublime settings"
mkdir -p ~/.config/sublime-text-3/Packages/User
cp sublime/LaTeXTools.sublime-settings ~/.config/sublime-text-3/Packages/User/.
cp sublime/Preferences.sublime-settings ~/.config/sublime-text-3/Packages/User/.
cp sublime/Package\ Control.sublime-settings ~/.config/sublime-text-3/Packages/User/.

echo "alias sub=sublime_text" >> ~/.bashrc

source ~/.bashrc

sub

