#!/bin/bash

echo_green "********************** Installing Sublime Text 3 ********************"
sudo add-apt-repository -y ppa:webupd8team/sublime-text-3
sudo apt-get update
sudo apt-get install sublime-text-installer

echo_blue "Setting Up Sublime Packages"
wget https://sublime.wbond.net/Package%20Control.sublime-package --no-check-certificate
mkdir -p ~/.config/sublime-text-3/Installed\ Packages
mv Package\ Control.sublime-package ~/.config/sublime-text-3/Installed\ Packages/

mkdir -p  ~/.config/sublime-text-3/Packages/User/Package\ Control
mkdir -p  ~/.config/sublime-text-3/Packages/User

echo_blue "installing Latex"
sudo apt-get install -y texlive latexmk

echo_blue "copying sublime settings"
mkdir -p ~/.config/sublime-text-3/Packages/User
cp sublime/LaTeXTools.sublime-settings ~/.config/sublime-text-3/Packages/User/.
cp sublime/Preferences.sublime-settings ~/.config/sublime-text-3/Packages/User/.
cp sublime/Package\ Control.sublime-settings ~/.config/sublime-text-3/Packages/User/.

echo "export PATH=\$PATH:/opt/sublime_text" >> ~/.bashrc
echo "alias sub=sublime_text" >> ~/.bashrc

source ~/.bashrc

sub

