#!/bin/bash

echo_green "Installing PyCharm"
wget https://download.jetbrains.com/python/pycharm-professional-2016.3.tar.gz
tar -xvf pycharm-professional-2016.3.tar.gz
sudo mv pycharm-2016.3 /opt/.
/opt/pycharm-2016.3/bin/pycharm.sh


