#!/bin/bash

sudo apt-get install -y latexmk
sudo apt-get install -y texlive-latex-recommended
sudo apt-get install -y texlive-latex-extra
sudo apt-get install -y texlive-fonts-recommended
sudo apt-get install -y texlive-fonts-extra
sudo apt-get install -y texlive-font-utils
sudo apt-get install -y texlive-pictures
sudo apt-get install -y texlive-science
sudo apt-get install -y texlive-math-extra
sudo apt-get install -y texlive-music
sudo apt-get install -y texlive-omega
