#!/bin/sh


#Install ROS
echo_green "Install ROS Indigo for Ubuntu 14.10 LTS Trusty based off of wiki.ros.org installation guide"
echo_blue "Setup your sources.list"

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'

echo_blue "Setup up your keys"

wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -O - | sudo apt-key add - 

echo_blue "Installation"

sudo apt-get update
sudo apt-get -y install ros-indigo-desktop-full

echo_blue "Initialize rosdep"

sudo rosdep init
rosdep update

echo_blue "Getting rosinstall"
sudo apt-get -y install python-rosinstall

echo_blue "Getting wstool"
sudo apt-get -y install python-wstool
