#!/bin/bash

echo "Install Environment? [Y/n]"
read ENVIRONMENT
if [ "$ENVIRONMENT" == 'n' ]; then
  bash Environment/color_functions/copy_color_functions
else
  Environment/install_environment
fi

echo_yellow "Install ROS Indigo? [Y/n]"
read INDIGO
if [ "$INDIGO" == 'n' ]; then
  echo_red "bypassing ROS indigo installation"
else
  ./install_indigo
fi

echo_yellow "Install additional ROS Packages? [Y/n]"
read PACKAGES
if [ "$PACKAGES" == 'n' ]; then
  echo_red "bypassing additional ROS Package installation"
else
  ./ros_packages
fi


echo_yellow "Install Google Chrome? [Y/n]"
read CHROME
if [ "$CHROME" == 'n' ]; then
  echo_red "bypassing Chrome installation"
else
  Programs/install_google_chrome
fi

echo_yellow "Install Sublime? [Y/n]"
read SUBLIME
if [ "$SUBLIME" == 'n' ]; then
  echo_red "bypassing Sublime Installation"
else
  Programs/install_sublime
fi

echo_yellow "Install QtCreator? [Y/n]"
read QT
if [ "$QT" == 'n' ]; then
  echo_red "bypassing QtCreator installation"
else
  Programs/install_qtcreator
fi

echo_yellow "Install Spotify? [Y/n]"
read SPOTIFY
if [ "$SPOTIFY" == 'n' ]; then
  echo_red "bypassing Spotify installation"
else
  Programs/install_spotify
fi

echo_yellow "Install Custom Theme? [Y/n]"
read THEME
if [ "$THEME" == 'n' ]; then
  echo_red "bypassing Theme installation"
else
  Themes/install_themes
fi
