#!/bin/sh

echo_green "**************************Installing QtCreator*********************************"

echo_blue "Downloading and Installing QtCreator"
wget http://mirrors.ocf.berkeley.edu/qt/archive/online_installers/3.0/qt-unified-linux-x64-3.0.4-online.run
sudo chmod +x qt-creator-opensource-linux-x86_64-4.1.0.run
sudo ./qt-creator-opensource-linux-x86_64-4.1.0.run

echo_blue "Copying IDE settings"
mkdir ~/.config/QtProject
cp -r qtcreator/settings ~/.config/QtProject/qtcreator

echo_blue "Fixing Icons"
sudo rm /usr/share/app-install/desktop/qtcreator:qtcreator.desktop
sudo cp qtcreator/qtcreator.desktop /usr/share/applications/.
