#!/bin/bash

wget http://desktop-download.mendeley.com/download/linux/mendeleydesktop-1.16.1-linux-x86_64.tar.bz2
tar -xvf mendeleydesktop-1.16.1-linux-x86_64.tar.bz2
sudo mv mendeleydesktop-1.16.1-linux-x86_64 /opt/mendeley
sudo cp mendeley.desktop /usr/share/applications/.


