#!/bin/bash
#sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
#sudo apt-get update
#sudo apt-get install -y gcc-arm-none-eabi=4.9.3.2015q3-1trusty1

git clone git://git.code.sf.net/p/stm32flash/code stm32flash-code
cd stm32flash-code
sudo make install
cd ..
rm -rf stm32flash-code
