#!/bin/bash

sudo apt-get install -y jstest-gtk
sudo rmmod xpad
sudo apt-get install --install-recommends jstest* joystick xboxdrv
echo "blacklist xpad" | sudo tee -a /etc/modprobe.d/blacklist.conf
sudo sed -i '$isudo xboxdrv --silent' /etc/rc.local
sudo xboxdrv --silent
